changelog:
  exclude:
    labels:
      - skip-release-notes
  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - docs
    - title: Maintenance
      labels:
        - chore
        - dependencies
        - refactor
