#!/usr/bin/env bash
set -eu

REPO="ssheeriin/super-kb"
INSTALL_ROOT="${SKB_INSTALL_ROOT:-$HOME/.local/opt/skb-mcp-server}"
BIN_DIR="${SKB_BIN_DIR:-$HOME/.local/bin}"
STATE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/skb-mcp-server"
MANIFEST_PATH="$STATE_DIR/install-manifest.sh"
REMOVE_CACHE=0
PROJECT_ROOT=""
YES=0

if [ -f "$MANIFEST_PATH" ]; then
  # Generated by install.sh for this user.
  # shellcheck disable=SC1090
  . "$MANIFEST_PATH"
fi

INSTALL_ROOT="${INSTALL_ROOT:-${SKB_INSTALL_ROOT:-$HOME/.local/opt/skb-mcp-server}}"
BIN_DIR="${BIN_DIR:-${SKB_BIN_DIR:-$HOME/.local/bin}}"
CURRENT_DIR="${CURRENT_DIR:-$INSTALL_ROOT/current}"
BIN_PATH="${BIN_PATH:-$BIN_DIR/skb-mcp-server}"
EXECUTABLE_PATH="${EXECUTABLE_PATH:-$CURRENT_DIR/skb-mcp-server}"
CLAUDE_SERVER_NAME="${CLAUDE_SERVER_NAME:-skb}"
CLAUDE_REGISTERED="${CLAUDE_REGISTERED:-0}"

usage() {
  cat <<'EOF'
Uninstall SKB from the current user account.

Usage:
  uninstall.sh [--install-root PATH] [--bin-dir PATH] [--remove-cache] [--remove-project-mcp PATH] [--yes]
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --install-root)
      INSTALL_ROOT="$2"
      CURRENT_DIR="$INSTALL_ROOT/current"
      EXECUTABLE_PATH="$CURRENT_DIR/skb-mcp-server"
      shift 2
      ;;
    --bin-dir)
      BIN_DIR="$2"
      BIN_PATH="$BIN_DIR/skb-mcp-server"
      shift 2
      ;;
    --remove-cache)
      REMOVE_CACHE=1
      shift
      ;;
    --remove-project-mcp)
      PROJECT_ROOT="$2"
      shift 2
      ;;
    --yes)
      YES=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [ "$YES" -eq 1 ]; then
  :
fi

remove_claude_server() {
  if ! command -v claude >/dev/null 2>&1; then
    echo "Claude Code CLI not found on PATH; skipping user MCP cleanup." >&2
    return
  fi

  claude_output=$(claude mcp get "$CLAUDE_SERVER_NAME" 2>&1 || true)
  if [ -z "$claude_output" ]; then
    return
  fi

  if [ "$CLAUDE_REGISTERED" = "1" ] || printf '%s' "$claude_output" | grep -F "$EXECUTABLE_PATH" >/dev/null 2>&1; then
    claude mcp remove "$CLAUDE_SERVER_NAME" -s user >/dev/null 2>&1 || true
    echo "Removed Claude MCP server '$CLAUDE_SERVER_NAME' from user config."
  fi
}

remove_project_mcp() {
  if [ -z "$PROJECT_ROOT" ]; then
    return
  fi
  if [ ! -x "$EXECUTABLE_PATH" ]; then
    echo "Cannot remove project .mcp.json entry because $EXECUTABLE_PATH is not available." >&2
    return
  fi
  "$EXECUTABLE_PATH" remove-mcp-config --project-root "$PROJECT_ROOT"
}

remove_project_mcp
remove_claude_server

if [ -e "$BIN_PATH" ]; then
  rm -f "$BIN_PATH"
  echo "Removed $BIN_PATH"
fi

if [ -d "$CURRENT_DIR" ]; then
  rm -rf "$CURRENT_DIR"
  echo "Removed $CURRENT_DIR"
fi

if [ -d "$INSTALL_ROOT" ]; then
  rmdir "$INSTALL_ROOT" 2>/dev/null || true
fi

if [ -f "$MANIFEST_PATH" ]; then
  rm -f "$MANIFEST_PATH"
fi
if [ -d "$STATE_DIR" ]; then
  rmdir "$STATE_DIR" 2>/dev/null || true
fi

if [ "$REMOVE_CACHE" -eq 1 ] && [ -d "$HOME/.skb" ]; then
  rm -rf "$HOME/.skb"
  echo "Removed $HOME/.skb"
fi

echo "SKB uninstall complete."
echo "Project-local .skb/, .claude/, and CLAUDE.md files were left untouched."
echo "If needed, remove them manually from specific repos."
